import {
  ChangeDetectionStrategy,
  Component,
  Input,
  TrackByFunction,
} from "@angular/core";
import { OlbSourceData } from "../../transaction-search/aml-transaction-search.service";
import { SelectionModel } from "@angular/cdk/collections";
import { IFilterForm } from "../../base-table/abstract-base-table";
import { BaseTableComponent } from "../../base-table/base-table.component";
import { TableSelectionCompareWithAmlTxnId } from "../transaction-view.component";

@Component({
  selector: "app-olb-table",
  imports: [BaseTableComponent],
  template: `
    <app-base-table
      [data]="this.olbSourceData"
      [dataColumnsValues]="dataColumnsValues"
      [dataColumnsIgnoreValues]="dataColumnsIgnoreValues"
      [displayedColumnsColumnHeaderMap]="displayedColumnsColumnHeaderMap"
      [stickyColumns]="stickyColumns"
      [selectFiltersValues]="selectFiltersValues"
      [dateFiltersValues]="dateFiltersValues"
      [dateFiltersValuesIgnore]="dateFiltersValuesIgnore"
      [displayedColumnsTime]="displayedColumnsTime"
      [dataSourceTrackBy]="dataSourceTrackBy"
      [selection]="selection"
      [hasMasterToggle]="false"
    />
  `,
  styleUrl: "./olb-table.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OlbTableComponent<
  TSelection extends { [K in keyof TableSelectionCompareWithAmlTxnId]: string },
> {
  dataColumnsValues: (keyof OlbSourceData)[] = [
    "postingDate",
    "transactionDate",
    "transactionTime",
    "transactionCurrencyAmount",
    "transactionCurrency",
    "transactionDescription",
    "transactionDescriptionBase",
    "transactionId",
    "userDeviceType",
    "userSessionDateTime",
    "userSessionDateTimeStr",
    "additionalDescription",
    "accountCurrency",
    "accountNumber",
    "acctCurrAmount",
    "acctHoldersAll",
    "actualCurrencyCD",
    "amlTransactionId",
    "cardNumber",
    "caseAccountNumber",
    "caseTransitNumber",
    "channelCd",
    "conductor",
    "crdrCode",
    "creditAmount",
    "creditedTransit",
    "creditedAccount",
    "creditorId",
    "currencyConversionRate",
    "cust2AddrCityTown",
    "cust2AddrPostalZipCode",
    "cust2AddrProvStateName",
    "cust2OrgLegalName",
    "customer1AccountHolderCifId",
    "customer1AccountStatus",
    "customer2AccountCurrencyCode",
    "customer2AccountHolderCifId",
    "customer2AccountStatus",
    "debitAmount",
    "debitedTransit",
    "debitedAccount",
    "flowOfFundsAccountCurrency",
    "flowOfFundsAmlId",
    "flowOfFundsCasePartyKey",
    "flowOfFundsConductorPartyKey",
    "flowOfFundsCreditAmount",
    "flowOfFundsCreditedAccount",
    "flowOfFundsCreditedTransit",
    "flowOfFundsDebitAmount",
    "flowOfFundsDebitedAccount",
    "flowOfFundsDebitedTransit",
    "flowOfFundsPostingDate",
    "flowOfFundsSource",
    "flowOfFundsSourceTransactionId",
    "flowOfFundsTransactionCurrency",
    "flowOfFundsTransactionCurrencyAmount",
    "flowOfFundsTransactionDate",
    "flowOfFundsTransactionDesc",
    "flowOfFundsTransactionTime",
    "executionLocalDateTime",
    "holdingBranchKey",
    "ipAddress",
    "messageTypeCode",
    "operationType",
    "oppAccountNumber",
    "oppBranchKey",
    "oppOrganizationUnitCd",
    "organizationUnitCd",
    "origCurrAmount",
    "origCurrCd",
    "processingDate",
    "rowUpdateDate",
    "rulesCADEquivalentAmt",
    "sourceTransactionId",
    "amlld",
    "caseEcif",
    "splittableColumnValue",
    "splittingDelimiter",
    "strCaAccount",
    "strCaAccountCurrency",
    "strCaAccountHolderCifId",
    "strCaAccountStatus",
    "strCaAmount",
    "strCaBeneficiaryInd",
    "strCaBranch",
    "strCaCurrency",
    "strCaDispositionType",
    "strCaDispositionTypeOpp",
    "strCaDispositionTypeOther",
    "strCaDispositionTypeOtherOpp",
    "strCaFiNumber",
    "strCaInvolvedInInd",
    "strReportingEntity",
    "strReportingEntityOpp",
    "strSaAccount",
    "strSaAccountCurrency",
    "strSaAccountHoldersCifId",
    "strSaAccountStatus",
    "strSaAmount",
    "strSaBranch",
    "strSaConductorInd",
    "strSaCurrency",
    "strSaDirection",
    "strSaDirectionOp",
    "strSaFiNumber",
    "strSaFundingSourceInd",
    "strSaFundsType",
    "strSaFundsTypeOpp",
    "strSaFundsTypeOther",
    "strSaFundsTypeOtherOpp",
    "strSaOboInd",
    "strSaPostingDate",
    "strTransactionStatus",
    "thirdPartyCifId",
    "_mongoid",
    "flowOfFundsAmlTransactionId",
  ];

  dataColumnsIgnoreValues: (keyof OlbSourceData)[] = [
    "accountCurrency",
    "accountNumber",
    "acctCurrAmount",
    "acctHoldersAll",
    "actualCurrencyCD",
    "amlTransactionId",
    "caseAccountNumber",
    "caseTransitNumber",
    "channelCd",
    "conductor",
    "crdrCode",
    "creditorId",
    "currencyConversionRate",
    "cust2AddrCityTown",
    "cust2AddrPostalZipCode",
    "cust2AddrProvStateName",
    "cust2OrgLegalName",
    "customer1AccountHolderCifId",
    "customer1AccountStatus",
    "customer2AccountCurrencyCode",
    "customer2AccountHolderCifId",
    "customer2AccountStatus",
    "flowOfFundsAccountCurrency",
    "flowOfFundsAmlId",
    "flowOfFundsCasePartyKey",
    "flowOfFundsConductorPartyKey",
    "flowOfFundsCreditAmount",
    "flowOfFundsCreditedAccount",
    "flowOfFundsCreditedTransit",
    "flowOfFundsDebitAmount",
    "flowOfFundsDebitedAccount",
    "flowOfFundsDebitedTransit",
    "flowOfFundsPostingDate",
    "flowOfFundsSource",
    "flowOfFundsSourceTransactionId",
    "flowOfFundsTransactionCurrency",
    "flowOfFundsTransactionCurrencyAmount",
    "flowOfFundsTransactionDate",
    "flowOfFundsTransactionDesc",
    "flowOfFundsTransactionTime",
    "executionLocalDateTime",
    "holdingBranchKey",
    "oppAccountNumber",
    "oppBranchKey",
    "oppOrganizationUnitCd",
    "organizationUnitCd",
    "origCurrAmount",
    "origCurrCd",
    "processingDate",
    "rowUpdateDate",
    "rulesCADEquivalentAmt",
    "splittableColumnValue",
    "splittingDelimiter",
    "strCaAccount",
    "strCaAccountCurrency",
    "strCaAccountHolderCifId",
    "strCaAccountStatus",
    "strCaAmount",
    "strCaBeneficiaryInd",
    "strCaBranch",
    "strCaCurrency",
    "strCaDispositionType",
    "strCaDispositionTypeOpp",
    "strCaDispositionTypeOther",
    "strCaDispositionTypeOtherOpp",
    "strCaFiNumber",
    "strCaInvolvedInInd",
    "strReportingEntity",
    "strReportingEntityOpp",
    "strSaAccount",
    "strSaAccountCurrency",
    "strSaAccountHoldersCifId",
    "strSaAccountStatus",
    "strSaAmount",
    "strSaBranch",
    "strSaConductorInd",
    "strSaCurrency",
    "strSaDirection",
    "strSaDirectionOp",
    "strSaFiNumber",
    "strSaFundingSourceInd",
    "strSaFundsType",
    "strSaFundsTypeOpp",
    "strSaFundsTypeOther",
    "strSaFundsTypeOtherOpp",
    "strSaOboInd",
    "strSaPostingDate",
    "strTransactionStatus",
    "thirdPartyCifId",
    "transactionDescriptionBase",
    "transactionId",
    "_mongoid",
    "userSessionDateTimeStr",
  ];

  displayedColumnsColumnHeaderMap: Partial<
    Record<
      | Extract<keyof OlbSourceData, string>
      | IFilterForm["filterFormFullTextFilterKey"]
      | (string & {}),
      string
    >
  > = {
    postingDate: "Posting Date",
    transactionDate: "Transaction Date",
    transactionTime: "Transaction Time",
    transactionCurrencyAmount: "Transaction Currency Amount",
    transactionCurrency: "Transaction Currency",
    transactionDescription: "Transaction Description",
    userDeviceType: "User Device Type",
    userSessionDateTime: "User Session",
    additionalDescription: "Additional Description",
    amlld: "AML ID",
    cardNumber: "Card Number",
    caseEcif: "Case ECIF",
    creditAmount: "Credit Amount",
    creditedAccount: "Credited Account",
    creditedTransit: "Credited Transit",
    debitAmount: "Debit Amount",
    debitedAccount: "Debited Account",
    debitedTransit: "Debited Transit",
    ipAddress: "IP Address",
    messageTypeCode: "Message Type Code",
    operationType: "Operation Type",
    sourceTransactionId: "Source Transaction ID",
    flowOfFundsAmlTransactionId: "Aml Transaction ID",
    fullTextFilterKey: "Full Text",
    _uiPropHighlightColor: "Highlight",
  };

  stickyColumns: ("select" | keyof OlbSourceData)[] = ["select"];

  selectFiltersValues: (keyof OlbSourceData)[] = [
    "transactionCurrencyAmount",
    "transactionCurrency",
    "transactionDescription",
    "userDeviceType",
    "userSessionDateTime",
    "userSessionDateTimeStr",
    "additionalDescription",
    "amlld",
    "cardNumber",
    "caseEcif",
    "creditAmount",
    "creditedAccount",
    "creditedTransit",
    "debitAmount",
    "debitedAccount",
    "debitedTransit",
    "sourceTransactionId",
  ];

  dateFiltersValues: (keyof OlbSourceData)[] = [
    "postingDate",
    "transactionDate",
  ];

  dateFiltersValuesIgnore: (keyof OlbSourceData)[] = ["transactionTime"];

  displayedColumnsTime: (keyof OlbSourceData)[] = ["transactionTime"];

  dataSourceTrackBy: TrackByFunction<OlbSourceData> = (_, record) => {
    return record.flowOfFundsAmlTransactionId;
  };

  @Input({ required: true })
  selection!: SelectionModel<TSelection>;

  @Input({ required: true })
  olbSourceData!: OlbSourceData[];
}
