import { CASE_RECORD_ID_DEV_OR_TEST_ONLY_FIXTURE } from '../../../aml/case-record.state.fixture';
import { StrTransactionWithChangeLogs } from '../../../aml/case-record.store';
import { StrTransaction } from '../../reporting-ui-table/reporting-ui-table.component';

export const MANUAL_TRANSACTIONS_DEV_OR_TEST_ONLY_FIXTURE: StrTransaction[] = [
  {
    wasTxnAttempted: false,
    wasTxnAttemptedReason: null,
    dateOfTxn: '2025/01/10',
    timeOfTxn: '18:46:23',
    hasPostingDate: null,
    dateOfPosting: null,
    timeOfPosting: null,
    methodOfTxn: 'ABM',
    methodOfTxnOther: null,
    reportingEntityTxnRefNo: 'ABM-01KCR084Y491T1YCKWF4VYRFXC',
    purposeOfTxn: null,
    reportingEntityLocationNo: '84255',
    _hiddenFullName: 'Kathlin Syphas',
    startingActions: [
      {
        _id: 'bbbe4d9f-2b36-4bbc-bb15-e8d8f27294d8',
        directionOfSA: 'Out',
        typeOfFunds: 'Funds Withdrawal',
        typeOfFundsOther: null,
        amount: 2300,
        currency: 'CAD',
        fiuNo: '010',
        branch: '84255',
        account: '5582195',
        accountType: 'Personal',
        accountTypeOther: null,
        accountOpen: '2003/08/24',
        accountClose: '',
        accountStatus: 'Active',
        accountCurrency: 'CAD',
        howFundsObtained: null,
        hasAccountHolders: true,
        accountHolders: [
          {
            _id: '278bdb03-ec4b-4bab-8705-f6f03c4cd772',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: '38ec0ae7-fac9-4aa6-9e81-658dac0f3445',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
        wasSofInfoObtained: true,
        sourceOfFunds: [],
        wasCondInfoObtained: true,
        conductors: [
          {
            _id: '4eaa9e12-a4ec-4f31-a13f-8a36e5410af0',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
            npdTypeOfDevice: null,
            npdTypeOfDeviceOther: null,
            npdDeviceIdNo: null,
            npdUsername: null,
            npdIp: null,
            npdDateTimeSession: null,
            npdTimeZone: null,
            wasConductedOnBehalf: null,
            onBehalfOf: null,
          },
        ],
      },
    ],
    _hiddenSaAmount: 2300,
    completingActions: [
      {
        _id: '26ca4d6c-4d48-4be5-9a91-a33c356c3588',
        detailsOfDispo: 'Cash Withdrawal',
        detailsOfDispoOther: null,
        amount: 2300,
        currency: 'CAD',
        exchangeRate: null,
        valueInCad: null,
        fiuNo: null,
        branch: null,
        account: null,
        accountType: null,
        accountTypeOther: null,
        accountCurrency: null,
        accountOpen: '',
        accountClose: null,
        accountStatus: null,
        hasAccountHolders: false,
        accountHolders: [],
        wasAnyOtherSubInvolved: false,
        involvedIn: [],
        wasBenInfoObtained: true,
        beneficiaries: [
          {
            _id: '011c8abc-6d7b-4b92-a0ec-6ea1ab77b235',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: '46c5cf84-9f8e-40d2-838a-1002ee7fdd1e',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
      },
    ],
    flowOfFundsAccountCurrency: 'CAD',
    flowOfFundsAmlId: 99999999,
    flowOfFundsAmlTransactionId: 'ABM-01KCR084Y491T1YCKWF4VYRFXC',
    flowOfFundsCasePartyKey: 3415674561,
    flowOfFundsConductorPartyKey: 3415674561,
    flowOfFundsCreditAmount: null,
    flowOfFundsCreditedAccount: null,
    flowOfFundsCreditedTransit: null,
    flowOfFundsDebitAmount: 2300,
    flowOfFundsDebitedAccount: '5582195',
    flowOfFundsDebitedTransit: '84255',
    flowOfFundsPostingDate: '2025/01/11',
    flowOfFundsSource: 'ABM',
    flowOfFundsSourceTransactionId: '005131',
    flowOfFundsTransactionCurrency: 'CAD',
    flowOfFundsTransactionCurrencyAmount: 2300,
    flowOfFundsTransactionDate: '2025/01/10',
    flowOfFundsTransactionDesc: 'Withdrawal @ 6 Warrior Lane, Tokoname, ON',
    flowOfFundsTransactionTime: '18:41:23',
    sourceId: 'Manual',
  },
  {
    wasTxnAttempted: false,
    wasTxnAttemptedReason: null,
    dateOfTxn: '2025/03/26',
    timeOfTxn: '16:02:58',
    hasPostingDate: null,
    dateOfPosting: null,
    timeOfPosting: null,
    methodOfTxn: 'ABM',
    methodOfTxnOther: null,
    reportingEntityTxnRefNo: 'ABM-01KCR08C0DM1Q6XSSV6KPMBY13',
    purposeOfTxn: null,
    reportingEntityLocationNo: '31980',
    _hiddenFullName: 'Anabel Benettelli',
    startingActions: [
      {
        _id: '77da0fc9-a04f-43ee-8b69-85833941e717',
        directionOfSA: 'Out',
        typeOfFunds: 'Funds Withdrawal',
        typeOfFundsOther: null,
        amount: 11700,
        currency: 'CAD',
        fiuNo: '010',
        branch: '31980',
        account: '8692413',
        accountType: 'Personal',
        accountTypeOther: null,
        accountOpen: '2001/07/14',
        accountClose: '',
        accountStatus: 'Active',
        accountCurrency: 'CAD',
        howFundsObtained: null,
        hasAccountHolders: true,
        accountHolders: [
          {
            _id: 'ddc8d7ca-f9ce-4afa-a137-a5488f55f6ce',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: '42e9fc66-74c5-452b-b12d-e6e5f7ce6c54',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
        wasSofInfoObtained: true,
        sourceOfFunds: [],
        wasCondInfoObtained: true,
        conductors: [
          {
            _id: 'bacc5c32-7453-HttpStatusCode.Conflict2-b9bd-de2df01aa1df',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
            npdTypeOfDevice: null,
            npdTypeOfDeviceOther: null,
            npdDeviceIdNo: null,
            npdUsername: null,
            npdIp: null,
            npdDateTimeSession: null,
            npdTimeZone: null,
            wasConductedOnBehalf: null,
            onBehalfOf: null,
          },
        ],
      },
    ],
    _hiddenSaAmount: 11700,
    completingActions: [
      {
        _id: '6fa813c0-39f3-49b7-a859-40cefd654426',
        detailsOfDispo: 'Cash Withdrawal',
        detailsOfDispoOther: null,
        amount: 11700,
        currency: 'CAD',
        exchangeRate: null,
        valueInCad: null,
        fiuNo: null,
        branch: null,
        account: null,
        accountType: null,
        accountTypeOther: null,
        accountCurrency: null,
        accountOpen: '',
        accountClose: null,
        accountStatus: null,
        hasAccountHolders: false,
        accountHolders: [],
        wasAnyOtherSubInvolved: false,
        involvedIn: [],
        wasBenInfoObtained: true,
        beneficiaries: [
          {
            _id: '1d8a908a-4330-4d94-a60e-72899af960fd',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: 'e76b063d-1e2b-4070-9554-71dbef832ccb',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
      },
    ],
    flowOfFundsAccountCurrency: 'CAD',
    flowOfFundsAmlId: 99999999,
    flowOfFundsAmlTransactionId: 'ABM-01KCR08C0DM1Q6XSSV6KPMBY13',
    flowOfFundsCasePartyKey: 3415674561,
    flowOfFundsConductorPartyKey: 1846597320,
    flowOfFundsCreditAmount: null,
    flowOfFundsCreditedAccount: null,
    flowOfFundsCreditedTransit: null,
    flowOfFundsDebitAmount: 11700,
    flowOfFundsDebitedAccount: '8692413',
    flowOfFundsDebitedTransit: '31980',
    flowOfFundsPostingDate: '2025/03/27',
    flowOfFundsSource: 'ABM',
    flowOfFundsSourceTransactionId: '008073',
    flowOfFundsTransactionCurrency: 'CAD',
    flowOfFundsTransactionCurrencyAmount: 11700,
    flowOfFundsTransactionDate: '2025/03/26',
    flowOfFundsTransactionDesc: 'Withdrawal @ 94190 Harper Park, Lundazi, ON',
    flowOfFundsTransactionTime: '15:57:58',
    sourceId: 'Manual',
  },
  {
    wasTxnAttempted: false,
    wasTxnAttemptedReason: null,
    dateOfTxn: '2024/07/28',
    timeOfTxn: '1:08:41',
    hasPostingDate: null,
    dateOfPosting: null,
    timeOfPosting: null,
    methodOfTxn: 'Online',
    methodOfTxnOther: null,
    reportingEntityTxnRefNo: 'OLB-01KCPEZ9B86KFCBV0YR6B7PCQP',
    purposeOfTxn: null,
    reportingEntityLocationNo: '84255',
    _hiddenFullName: 'Gelya Caughan',
    startingActions: [
      {
        _id: '6938792a-83fb-4a96-b44d-ac7b5668b541',
        directionOfSA: 'Out',
        typeOfFunds: 'Funds Withdrawal',
        typeOfFundsOther: null,
        amount: 3120,
        currency: 'CAD',
        fiuNo: '010',
        branch: '84255',
        account: '5582195',
        accountType: 'Personal',
        accountTypeOther: null,
        accountOpen: '2005/06/23',
        accountClose: null,
        accountStatus: 'Active',
        accountCurrency: 'CAD',
        howFundsObtained: null,
        hasAccountHolders: true,
        accountHolders: [
          {
            _id: '525c8975-fd77-4763-b16b-b1c3d688356c',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: '73ab698e-3c33-4924-9ac0-f316a997fb72',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
        wasSofInfoObtained: false,
        sourceOfFunds: [],
        wasCondInfoObtained: true,
        conductors: [
          {
            _id: 'da5d33a9-636d-4f6e-ab9b-46591b091307',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: null,
            npdTypeOfDevice: 'Internet',
            npdTypeOfDeviceOther: '',
            npdDeviceIdNo: null,
            npdUsername: null,
            npdIp: '29.38.241.91',
            npdDateTimeSession: '2024-07-28T00:00:00Z',
            npdTimeZone: null,
            wasConductedOnBehalf: false,
            onBehalfOf: null,
          },
        ],
      },
    ],
    _hiddenSaAmount: 3120,
    completingActions: [
      {
        _id: 'e90e636b-89e4-42d7-b443-6026d657e558',
        detailsOfDispo: 'Outgoing email money transfer',
        detailsOfDispoOther: null,
        amount: 3120,
        currency: 'CAD',
        exchangeRate: null,
        valueInCad: null,
        fiuNo: '010',
        branch: '16490',
        account: '1509461',
        accountType: 'Personal',
        accountTypeOther: null,
        accountCurrency: 'CAD',
        accountOpen: '10/31/2017',
        accountClose: null,
        accountStatus: 'Active',
        hasAccountHolders: true,
        accountHolders: [
          {
            _id: '9bf92dbe-db57-4e80-b023-3b47ed6fc400',
            linkToSub: '',
            _hiddenPartyKey: '5584348274',
            _hiddenSurname: 'Downer',
            _hiddenGivenName: 'Case',
            _hiddenOtherOrInitial: '',
            _hiddenNameOfEntity: null,
          },
        ],
        wasAnyOtherSubInvolved: false,
        involvedIn: [],
        wasBenInfoObtained: true,
        beneficiaries: [
          {
            _id: '8d2a7f7a-cee0-4800-9161-d69d5c044e0c',
            linkToSub: '',
            _hiddenPartyKey: '5584348274',
            _hiddenSurname: 'Downer',
            _hiddenGivenName: 'Case',
            _hiddenOtherOrInitial: '',
            _hiddenNameOfEntity: null,
          },
        ],
      },
    ],
    flowOfFundsAccountCurrency: 'CAD',
    flowOfFundsAmlId: 99999999,
    flowOfFundsAmlTransactionId: 'OLB-01KCPEZ9B86KFCBV0YR6B7PCQP',
    flowOfFundsCasePartyKey: 3415674561,
    flowOfFundsConductorPartyKey: 3415674561,
    flowOfFundsCreditAmount: null,
    flowOfFundsCreditedAccount: null,
    flowOfFundsCreditedTransit: null,
    flowOfFundsDebitAmount: 3120,
    flowOfFundsDebitedAccount: '5582195',
    flowOfFundsDebitedTransit: '84255',
    flowOfFundsPostingDate: '2024/07/29',
    flowOfFundsSource: 'OLB',
    flowOfFundsSourceTransactionId: '100534260128',
    flowOfFundsTransactionCurrency: 'CAD',
    flowOfFundsTransactionCurrencyAmount: 3120,
    flowOfFundsTransactionDate: '2024/07/28',
    flowOfFundsTransactionDesc: 'Send E-Transfer @ case',
    flowOfFundsTransactionTime: '01:03:41',
    sourceId: 'Manual',
  },
  {
    wasTxnAttempted: false,
    wasTxnAttemptedReason: null,
    dateOfTxn: '2025/04/14',
    timeOfTxn: '2:57:01',
    hasPostingDate: null,
    dateOfPosting: null,
    timeOfPosting: null,
    methodOfTxn: 'Online',
    methodOfTxnOther: null,
    reportingEntityTxnRefNo: 'OLB-01KCPEZGH4RPRRJRMF2BHNAXRD',
    purposeOfTxn: null,
    reportingEntityLocationNo: '31980',
    _hiddenFullName: 'Barbi Geekin',
    startingActions: [
      {
        _id: 'f26c5032-81e4-4641-9ce0-24077181f8c6',
        directionOfSA: 'Out',
        typeOfFunds: 'Funds Withdrawal',
        typeOfFundsOther: null,
        amount: 2480,
        currency: 'CAD',
        fiuNo: '010',
        branch: '31980',
        account: '8692413',
        accountType: 'Personal',
        accountTypeOther: null,
        accountOpen: '2001/07/14',
        accountClose: null,
        accountStatus: 'Active',
        accountCurrency: 'CAD',
        howFundsObtained: null,
        hasAccountHolders: true,
        accountHolders: [
          {
            _id: 'c606243b-b990-4053-881d-df739e0784a8',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: '5d5aefdf-118f-481c-9c63-d875c2a5d9c6',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
        wasSofInfoObtained: false,
        sourceOfFunds: [],
        wasCondInfoObtained: true,
        conductors: [
          {
            _id: 'c6bfbe19-1d6e-HttpStatusCode.Conflict7-bf08-31e2108fdc33',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: null,
            npdTypeOfDevice: 'Internet',
            npdTypeOfDeviceOther: '',
            npdDeviceIdNo: null,
            npdUsername: null,
            npdIp: '125.127.124.115',
            npdDateTimeSession: '2025-04-14T00:00:00Z',
            npdTimeZone: null,
            wasConductedOnBehalf: false,
            onBehalfOf: null,
          },
        ],
      },
    ],
    _hiddenSaAmount: 2480,
    completingActions: [
      {
        _id: '96f67015-3c17-420e-933d-c073abfcaf4f',
        detailsOfDispo: 'Outgoing email money transfer',
        detailsOfDispoOther: null,
        amount: 2480,
        currency: 'CAD',
        exchangeRate: null,
        valueInCad: null,
        fiuNo: '010',
        branch: '88272',
        account: '1127288',
        accountType: 'Personal',
        accountTypeOther: null,
        accountCurrency: 'CAD',
        accountOpen: '9/21/2005',
        accountClose: null,
        accountStatus: 'Active',
        hasAccountHolders: true,
        accountHolders: [
          {
            _id: '1abbdd6b-cc1f-4e6d-a720-efe959196010',
            linkToSub: '',
            _hiddenPartyKey: '0919006056',
            _hiddenSurname: 'Ramard',
            _hiddenGivenName: 'Ally',
            _hiddenOtherOrInitial: '',
            _hiddenNameOfEntity: null,
          },
        ],
        wasAnyOtherSubInvolved: false,
        involvedIn: [],
        wasBenInfoObtained: true,
        beneficiaries: [
          {
            _id: '5adad2db-ea31-4403-8619-f0740066d84f',
            linkToSub: '',
            _hiddenPartyKey: '0919006056',
            _hiddenSurname: 'Ramard',
            _hiddenGivenName: 'Ally',
            _hiddenOtherOrInitial: '',
            _hiddenNameOfEntity: null,
          },
        ],
      },
    ],
    flowOfFundsAccountCurrency: 'CAD',
    flowOfFundsAmlId: 99999999,
    flowOfFundsAmlTransactionId: 'OLB-01KCPEZGH4RPRRJRMF2BHNAXRD',
    flowOfFundsCasePartyKey: 3415674561,
    flowOfFundsConductorPartyKey: 3415674561,
    flowOfFundsCreditAmount: null,
    flowOfFundsCreditedAccount: null,
    flowOfFundsCreditedTransit: null,
    flowOfFundsDebitAmount: 2480,
    flowOfFundsDebitedAccount: '8692413',
    flowOfFundsDebitedTransit: '31980',
    flowOfFundsPostingDate: '2025/04/15',
    flowOfFundsSource: 'OLB',
    flowOfFundsSourceTransactionId: '100719182403',
    flowOfFundsTransactionCurrency: 'CAD',
    flowOfFundsTransactionCurrencyAmount: 2480,
    flowOfFundsTransactionDate: '2025/04/14',
    flowOfFundsTransactionDesc: 'Send E-Transfer @ ally',
    flowOfFundsTransactionTime: '02:52:01',
    sourceId: 'Manual',
  },
  {
    wasTxnAttempted: false,
    wasTxnAttemptedReason: null,
    dateOfTxn: '2024/07/03',
    timeOfTxn: '6:42:31',
    hasPostingDate: null,
    dateOfPosting: null,
    timeOfPosting: null,
    methodOfTxn: 'Online',
    methodOfTxnOther: null,
    reportingEntityTxnRefNo: 'OLB-01KCPEZJ7X56G5PPEQYVCTFCCH',
    purposeOfTxn: null,
    reportingEntityLocationNo: '87594',
    _hiddenFullName: 'Sela Hugo',
    startingActions: [
      {
        _id: 'f9350d9a-5e5d-488d-842f-e8ba3868d2bf',
        directionOfSA: 'Out',
        typeOfFunds: 'Funds Withdrawal',
        typeOfFundsOther: null,
        amount: 2370,
        currency: 'CAD',
        fiuNo: '010',
        branch: '87594',
        account: '5647218',
        accountType: 'Personal',
        accountTypeOther: null,
        accountOpen: '2003/08/24',
        accountClose: null,
        accountStatus: 'Active',
        accountCurrency: 'CAD',
        howFundsObtained: null,
        hasAccountHolders: true,
        accountHolders: [
          {
            _id: '68874d67-fde2-49b1-9d0a-f558307ba3d8',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: '827a53b0-07f1-4462-bafc-c89c64770ba8',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
        wasSofInfoObtained: false,
        sourceOfFunds: [],
        wasCondInfoObtained: true,
        conductors: [
          {
            _id: 'e6f61c89-8184-4d6a-acfb-ada51677508b',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: null,
            npdTypeOfDevice: 'Internet',
            npdTypeOfDeviceOther: '',
            npdDeviceIdNo: null,
            npdUsername: null,
            npdIp: '103.93.216.188',
            npdDateTimeSession: '2024-07-03T00:00:00Z',
            npdTimeZone: null,
            wasConductedOnBehalf: false,
            onBehalfOf: null,
          },
        ],
      },
    ],
    _hiddenSaAmount: 2370,
    completingActions: [
      {
        _id: '4cc55ad9-6a7b-40d4-ab09-5ad75a1402b3',
        detailsOfDispo: 'Outgoing email money transfer',
        detailsOfDispoOther: null,
        amount: 2370,
        currency: 'CAD',
        exchangeRate: null,
        valueInCad: null,
        fiuNo: '010',
        branch: '20392',
        account: '1229302',
        accountType: 'Personal',
        accountTypeOther: null,
        accountCurrency: 'CAD',
        accountOpen: '12/15/2008',
        accountClose: null,
        accountStatus: 'Active',
        hasAccountHolders: true,
        accountHolders: [
          {
            _id: '15d3bc94-7c6f-40a0-b0b0-f02d47d3a796',
            linkToSub: '',
            _hiddenPartyKey: '9446370267',
            _hiddenSurname: 'Kelle',
            _hiddenGivenName: 'Dmitri',
            _hiddenOtherOrInitial: '',
            _hiddenNameOfEntity: null,
          },
        ],
        wasAnyOtherSubInvolved: false,
        involvedIn: [],
        wasBenInfoObtained: true,
        beneficiaries: [
          {
            _id: '65d51eb5-e891-4ed3-865f-7fe3a333ba01',
            linkToSub: '',
            _hiddenPartyKey: '9446370267',
            _hiddenSurname: 'Kelle',
            _hiddenGivenName: 'Dmitri',
            _hiddenOtherOrInitial: '',
            _hiddenNameOfEntity: null,
          },
        ],
      },
    ],
    flowOfFundsAccountCurrency: 'CAD',
    flowOfFundsAmlId: 99999999,
    flowOfFundsAmlTransactionId: 'OLB-01KCPEZJ7X56G5PPEQYVCTFCCH',
    flowOfFundsCasePartyKey: 3415674561,
    flowOfFundsConductorPartyKey: 3415674561,
    flowOfFundsCreditAmount: null,
    flowOfFundsCreditedAccount: null,
    flowOfFundsCreditedTransit: null,
    flowOfFundsDebitAmount: 2370,
    flowOfFundsDebitedAccount: '5647218',
    flowOfFundsDebitedTransit: '87594',
    flowOfFundsPostingDate: '2024/07/04',
    flowOfFundsSource: 'OLB',
    flowOfFundsSourceTransactionId: '106156429501',
    flowOfFundsTransactionCurrency: 'CAD',
    flowOfFundsTransactionCurrencyAmount: 2370,
    flowOfFundsTransactionDate: '2024/07/03',
    flowOfFundsTransactionDesc: 'Send E-Transfer @ dmitri',
    flowOfFundsTransactionTime: '06:37:31',
    sourceId: 'Manual',
  },
  {
    wasTxnAttempted: false,
    wasTxnAttemptedReason: null,
    dateOfTxn: '2025/02/19',
    timeOfTxn: '04:55:12',
    hasPostingDate: false,
    dateOfPosting: null,
    timeOfPosting: null,
    methodOfTxn: 'In-Person',
    methodOfTxnOther: null,
    reportingEntityTxnRefNo: 'IWS-10PW-ecfda42b-f372-4d41-9127-dc199ef5cfef',
    purposeOfTxn: 'INV 68127811\nTO PAY AN INVOICE',
    reportingEntityLocationNo: '43804',
    startingActions: [
      {
        _id: 'b776798f-9b9a-43f1-a5ad-c640a06accc1',
        directionOfSA: 'In',
        typeOfFunds: 'International Funds Transfer',
        typeOfFundsOther: null,
        amount: 91684,
        currency: 'CAD',
        fiuNo: 'SBININBB582',
        branch: null,
        account: 'UXU19924',
        accountType: null,
        accountTypeOther: null,
        accountOpen: null,
        accountClose: null,
        accountStatus: null,
        accountCurrency: null,
        howFundsObtained: null,
        hasAccountHolders: false,
        accountHolders: [],
        wasSofInfoObtained: false,
        sourceOfFunds: [],
        wasCondInfoObtained: true,
        conductors: [
          {
            _id: 'e60e6404-9be3-462a-882e-ac8f45f3ee14',
            linkToSub: '',
            _hiddenPartyKey: null,
            _hiddenSurname: null,
            _hiddenGivenName: null,
            _hiddenOtherOrInitial: null,
            _hiddenNameOfEntity: 'Topiczoom',
            npdTypeOfDevice: null,
            npdTypeOfDeviceOther: null,
            npdDeviceIdNo: null,
            npdUsername: null,
            npdIp: null,
            npdDateTimeSession: null,
            npdTimeZone: null,
            wasConductedOnBehalf: false,
            onBehalfOf: null,
          },
        ],
      },
    ],
    completingActions: [
      {
        _id: '81f03b66-1639-44f7-9621-372b1e1dae58',
        detailsOfDispo: 'Deposit to account',
        detailsOfDispoOther: null,
        amount: 91684,
        currency: 'CAD',
        exchangeRate: null,
        valueInCad: null,
        fiuNo: '010',
        branch: '84255',
        account: '5582195',
        accountType: 'Personal',
        accountTypeOther: null,
        accountCurrency: 'CAD',
        accountOpen: '2003/08/24',
        accountClose: '',
        accountStatus: 'Active',
        hasAccountHolders: true,
        accountHolders: [
          {
            _id: '8c412787-c1e7-4518-b8b9-9c86b0a36255',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: '97faf2f7-4ecc-4346-b0d9-a0cc2fd4c209',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
        wasAnyOtherSubInvolved: false,
        involvedIn: [],
        wasBenInfoObtained: true,
        beneficiaries: [
          {
            _id: 'c874163f-71a2-47c3-9de3-f331f48174f7',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: '6492cd0d-19ab-44c7-95ee-8df366b3b810',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
      },
    ],
    flowOfFundsAccountCurrency: 'CAD',
    flowOfFundsAmlId: 99999999,
    flowOfFundsAmlTransactionId:
      'IWS-10PW-ecfda42b-f372-4d41-9127-dc199ef5cfef',
    flowOfFundsCasePartyKey: 3415674561,
    flowOfFundsConductorPartyKey: null,
    flowOfFundsCreditAmount: 41286,
    flowOfFundsCreditedAccount: '8692413',
    flowOfFundsCreditedTransit: '84255',
    flowOfFundsDebitAmount: null,
    flowOfFundsDebitedAccount: null,
    flowOfFundsDebitedTransit: null,
    flowOfFundsPostingDate: '2025/02/19',
    flowOfFundsSource: 'Wires',
    flowOfFundsSourceTransactionId: 'T0250219560279243',
    flowOfFundsTransactionCurrency: 'CAD',
    flowOfFundsTransactionCurrencyAmount: 41286,
    flowOfFundsTransactionDate: '2025/02/19',
    flowOfFundsTransactionDesc:
      'Incoming Wire @ Aivee\nHauptstraße, 401\nLazaro Cardenas\n87326 MX',
    flowOfFundsTransactionTime: '04:55:12',
    sourceId: 'Manual',
  },
  {
    wasTxnAttempted: false,
    wasTxnAttemptedReason: null,
    dateOfTxn: '2025/01/14',
    timeOfTxn: '16:28:30',
    hasPostingDate: false,
    dateOfPosting: null,
    timeOfPosting: null,
    methodOfTxn: 'In-Person',
    methodOfTxnOther: null,
    reportingEntityTxnRefNo: 'IWS-10PW-0ad115b5-e816-4cf6-8d19-363de0c377c9',
    purposeOfTxn: 'INV 97533022\nTO PAY AN INVOICE',
    reportingEntityLocationNo: '84255',
    startingActions: [
      {
        _id: '9b266678-e6f9-43cb-b2d5-6c5cc8d0c48d',
        directionOfSA: 'In',
        typeOfFunds: 'International Funds Transfer',
        typeOfFundsOther: null,
        amount: 91684,
        currency: 'CAD',
        fiuNo: 'SBININBB582',
        branch: null,
        account: 'UXU19924',
        accountType: null,
        accountTypeOther: null,
        accountOpen: null,
        accountClose: null,
        accountStatus: null,
        accountCurrency: null,
        howFundsObtained: null,
        hasAccountHolders: false,
        accountHolders: [],
        wasSofInfoObtained: false,
        sourceOfFunds: [],
        wasCondInfoObtained: true,
        conductors: [
          {
            _id: 'ae41f3d2-0912-4320-bcdc-9b94facb2b17',
            linkToSub: '',
            _hiddenPartyKey: null,
            _hiddenSurname: null,
            _hiddenGivenName: null,
            _hiddenOtherOrInitial: null,
            _hiddenNameOfEntity: 'Topiczoom',
            npdTypeOfDevice: null,
            npdTypeOfDeviceOther: null,
            npdDeviceIdNo: null,
            npdUsername: null,
            npdIp: null,
            npdDateTimeSession: null,
            npdTimeZone: null,
            wasConductedOnBehalf: false,
            onBehalfOf: null,
          },
        ],
      },
    ],
    completingActions: [
      {
        _id: '57fb3e7f-c498-46d9-9743-8a7ea27c3282',
        detailsOfDispo: 'Deposit to account',
        detailsOfDispoOther: null,
        amount: 91684,
        currency: 'CAD',
        exchangeRate: null,
        valueInCad: null,
        fiuNo: '010',
        branch: '84255',
        account: '5582195',
        accountType: 'Personal',
        accountTypeOther: null,
        accountCurrency: 'CAD',
        accountOpen: '2003/08/24',
        accountClose: '',
        accountStatus: 'Active',
        hasAccountHolders: true,
        accountHolders: [
          {
            _id: '76aa7f23-6d4f-4fa0-bc36-d0f21cf7ee0f',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: 'ae57e6aa-11aa-40e1-9f99-457729675b87',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
        wasAnyOtherSubInvolved: false,
        involvedIn: [],
        wasBenInfoObtained: true,
        beneficiaries: [
          {
            _id: 'fd2b6fe1-c29e-4b0c-b2f3-8b8e27f75b7e',
            linkToSub: '',
            _hiddenPartyKey: '3415674561',
            _hiddenSurname: 'Carter',
            _hiddenGivenName: 'James',
            _hiddenOtherOrInitial: 'L',
            _hiddenNameOfEntity: '',
          },
          {
            _id: 'b8d87990-7812-404a-a81e-12cec45f19cc',
            linkToSub: '',
            _hiddenPartyKey: '1846597320',
            _hiddenSurname: 'Nguyen',
            _hiddenGivenName: 'Laura',
            _hiddenOtherOrInitial: 'M',
            _hiddenNameOfEntity: '',
          },
        ],
      },
    ],
    flowOfFundsAccountCurrency: 'CAD',
    flowOfFundsAmlId: 99999999,
    flowOfFundsAmlTransactionId:
      'IWS-10PW-0ad115b5-e816-4cf6-8d19-363de0c377c9',
    flowOfFundsCasePartyKey: 3415674561,
    flowOfFundsConductorPartyKey: null,
    flowOfFundsCreditAmount: 91331,
    flowOfFundsCreditedAccount: '5647218',
    flowOfFundsCreditedTransit: '84255',
    flowOfFundsDebitAmount: null,
    flowOfFundsDebitedAccount: null,
    flowOfFundsDebitedTransit: null,
    flowOfFundsPostingDate: '2025/01/14',
    flowOfFundsSource: 'Wires',
    flowOfFundsSourceTransactionId: 'T0250114734345514',
    flowOfFundsTransactionCurrency: 'CAD',
    flowOfFundsTransactionCurrencyAmount: 91331,
    flowOfFundsTransactionDate: '2025/01/14',
    flowOfFundsTransactionDesc:
      'Incoming Wire @ Photojam\nPIAZZA FILIPPO MEDA 4\nStavanger\n4064 NO',
    flowOfFundsTransactionTime: '16:28:30',
    sourceId: 'Manual',
  },
];

export const MANUAL_TRANSACTIONS_WITH_CHANGELOGS_DEV_OR_TEST_ONLY_FIXTURE =
  MANUAL_TRANSACTIONS_DEV_OR_TEST_ONLY_FIXTURE.map((txn) => ({
    ...txn,
    caseRecordId: CASE_RECORD_ID_DEV_OR_TEST_ONLY_FIXTURE,
    _hiddenTxnType: txn.flowOfFundsSource,
    _hiddenAmlId: '999999',
    _hiddenStrTxnId: txn.flowOfFundsAmlTransactionId,
    changeLogs: [],
    eTag: 0
  })) satisfies StrTransactionWithChangeLogs[];
